In [ ]:
# ndarray 생성
import numpy as np

# python의 list : []
a = [1,2,3,4]
print("a list의 내용은 : {}".format(a))
# python은 모든 데이터는 당연히 객체 (객체는 class로부터 파생)
# python에서 객체의 class를 알아내는 함수는 type()
print( type(a) )

a list의 내용은 : [1, 2, 3, 4]
<class 'list'>


In [ ]:
# ndarray 생성 실습
# 가장 대표적인 방법 : list 이용
b = np.array([1, 2, 3, 4])
print('ndarray는 : {}'.format(b))
print(type(b))

ndarray는 : [1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
#np.nan : numpy의 상수값 -> null값이라고 생각하면 된다
#이때의 nan은 실수로 간주

# 배열의 대표적인 특징
# 1. 사이즈 결정 후 변경 불가
# 2. 모든 데이터는 같은 데이터 타입을 가짐
# 따라서 처음에 사이즈 결정을 하고 비어있는 데이터를 nan이라는 상수로 자리 메꾸기
my_list = [[1,2,3], [4,5,np.nan]]
arr = np.array(my_list)
print(arr)
print(arr[0,2])
print(arr[0][2])
# indexing을 잘할 수 있어야 함 -> 원하는 데이터를 바로바로 가져올 수 있도록 해야한다!

[[ 1.  2.  3.]
 [ 4.  5. nan]]
3.0
3.0


In [ ]:
#ndarray 주요 속성
a = [1,2,3,4]
arr1 = np.array(a)
print(arr1)
print(arr1.ndim)  # 1 (몇 차원인지 알려줌)
print(arr1.shape) #python tuple로 출력
# tuple은 list와 유사한 자료구조 (list와 다른점 = read only)
# shape은 차원 수와 각 차원의 요소 개수를 동시에 출렭
print(arr.shape)



[1 2 3 4]
1
(4,)
(2, 3)


In [ ]:
# 데이터 타입을 바꾸기
arr = np.array([1.2, 3.4, 5.6, 7.8, 9.1])
print(arr)
# ndarry는 모든 요소의 데이터 타입이 같음
# arr.astype(np.int32) # 소수점 이하는 버림처리
arr1 = arr.astype(np.int32)
print(arr1)

[1.2 3.4 5.6 7.8 9.1]
[1 3 5 7 9]


In [ ]:
# 다른방식으로 ndarray 만들어보기
# 제공되는 함수들을 이용해서 ndarray 만들기
arr1 = np.zeros((3,4))
print(arr1)
arr2 = np.ones((2,3))
print(arr2)
#원하는 값으로 채우려면 어떻게 해야 하나?
arr3 = np.full((2,3), 7, dtype=np.float32)
print(arr3)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7. 7. 7.]
 [7. 7. 7.]]


In [ ]:
# 1부터 16까지 숫자를 이용해서
# 2차원 ndarray(4,4)를 만들어요!
arr = np.arange(1,17,1).reshape(4,4)
# print(arr)

# 이 안에 10보다 큰 수가 몇개 있는지 알고싶어요!
(arr > 10).sum()

6

In [9]:
cd /content/drive/MyDrive/KOSA3/deep_learning

/content/drive/MyDrive/KOSA3/deep_learning


In [10]:
!git config --global user.email 'o.ov0227@gmail.com'
!git config --global user.name 'jihyun-log'

In [11]:
!git add 1020-Numpy.ipynb

In [12]:
!git commit -m 'Numpy 이론 및 실습'
!git push

[main df9c310] Numpy 이론 및 실습
 1 file changed, 1 insertion(+)
 create mode 100644 1020-Numpy.ipynb
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 2.75 KiB | 563.00 KiB/s, done.
Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
To https://github.com/jihyun-log/deep_learning.git
   aa4076a..df9c310  main -> main
